#!/bin/sh

if [ "start" == "$1" ]; then
	echo "Loading modules on startup."
	start-stop-daemon -S -n init -a /bin/scull_load
	start-stop-daemon -S -n init -a /bin/module_load -- faulty
	start-stop-daemon -S -n init -a /bin/module_load -- hello
else
	echo "Removing modules (shutdown?)"
	start-stop-daemon -K -n scull_load
	start-stop-daemon -K -n module_load
	start-stop-daemon -S -n init -a /bin/scull_unload
	start-stop-daemon -S -n init -a /bin/module_unload -- faulty
	start-stop-daemon -S -n init -a /bin/module_unload -- hello
fi
